### ISSUE TITLE
ClassNotFoundException SystemAdapter & BenchmarkController

### ISSUE THREAD

**Issue by oshando** [hobbit-project/java-sdk#1]
When I attempt to run ExampleBenchmarkTest, I get a ClassNotFoundException for the SystemAdapter and BenchmarkController classes and program stops.

**Comment by smirnp** [comment]
Coul you please provide stack trace?

**Comment by oshando** [comment]
The problem seems to have resolved automatically after attempting to run it a few times. Thanks.
