### ISSUE TITLE
KeyValue can't store array values

### ISSUE THREAD

**Issue by denkv** [hobbit-project/java-sdk#3]
Setting an array value is included in `KeyValueTest`:

```java
KeyValue kv = new KeyValue();
kv.setValue("property3", new String[]{ "value3", "value4" });
```

But it doesn't properly handle it, leading to failing test.

If we don't need any array values there, we can remove this from the test and add a throw when trying to add an array value to KeyValue.

**Comment by smirnp** [comment]
Fixed in the last commit
